version: '3.1'
services:
  teamspeak:
    image: teamspeak
    restart: always
    ports:
      - 9987:9987/udp
      - 30033:30033
    environment:
      TS3SERVER_DB_PLUGIN: ts3db_mariadb
      TS3SERVER_DB_SQLCREATEPATH: create_mariadb
      TS3SERVER_DB_HOST: db
      TS3SERVER_DB_USER: root
      TS3SERVER_DB_PASSWORD: '{{ mysql_password }}'
      TS3SERVER_DB_NAME: teamspeak
      TS3SERVER_DB_WAITUNTILREADY: 30
      TS3SERVER_LICENSE: accept
    restart: unless-stopped
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '{{ mysql_password }}'
      MYSQL_DATABASE: teamspeak
    restart: unless-stopped
