---
version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.5.0
    user: "0"
    volumes:
      - ./loki:/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    user: "0"
    volumes:
      - ./grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - loki
    restart: unless-stopped
