---
- hosts: localhost

  roles:
    - role: lebergarrett.ansible_nfs_client
      vars:
        sharedrive_location: truenasv2.kumpdev.com:/mnt/Primary/nfs
    - role: ../../roles/install-common-packages
    - role: ../../roles/git-setup
      vars:
        git_user: lebergarrett
        git_email: lebergarrett@gmail.com
    - role: ../../roles/prezto
    - role: ../../roles/dotfiles
    - role: ../../roles/vimplug
    - role: ../../roles/sudoers
    - role: ../../roles/upgrade
