---
- hosts: localhost

  roles:
    - role: lebergarrett.ansible_nfs_client
      vars:
        sharedrive_location: truenasv2.kumpdev.com:/mnt/Primary/nfs
    - role: install-common-packages
    - role: git-setup
      vars:
        git_user: lebergarrett
        git_email: lebergarrett@gmail.com
    - role: prezto
    - role: dotfiles
    - role: vimplug
    - role: sudoers
    - role: upgrade
