---
- include: debian.yml
  when: ansible_os_family == 'Debian'

- include: macos.yml
  when: ansible_os_family == 'Darwin'

- include: arch.yml
  when: ansible_os_family == 'Archlinux'

- include: redhat.yml
  when: ansible_os_family == 'RedHat'
