---
- hosts: dockerhost
  gather_facts: true
  become: true
  # vars_files:
  #   - ../vault.yaml
  roles:
    - role: lebergarrett.ansible_common_debian
    - role: lebergarrett.ansible_nfs_client
      vars:
        sharedrive_location: truenasv2.kumpdev.com:/mnt/Primary/nfs
    - role: lebergarrett.ansible_awscli
    - role: geerlingguy.docker
      vars:
        docker_install_compose: true
        docker_users:
          - lab

  # tasks:
  #   - name: Install pip3
  #     apt:
  #       name: python3-pip
  #       state: present

  #   - name: install certain python modules for docker
  #     pip:
  #       name: docker
  #       version: "5.0.3"
  #       state: present

  #   - name: Create the docker network for traefik
  #     community.general.docker_network:
  #       name: web
  #     vars:
  #       ansible_python_interpreter: /bin/python3

  #   - name: Create the directory for traefik config
  #     ansible.builtin.file:
  #       path: /opt/traefik
  #       state: directory
  #       mode: '0755'
    
  #   - name: Create the docker-compose file for traefik
  #     ansible.builtin.copy:
  #       src: files/docker-compose.yml
  #       dest: /opt/traefik/docker-compose.yml
  #       mode: 0644

  #   - name: Copy traefik config file
  #     ansible.builtin.copy:
  #       src: files/traefik.toml
  #       dest: /opt/traefik/traefik.toml
  #       mode: 0644
    
  #   - name: Touch acme file and set perms
  #     ansible.builtin.file:
  #       path: /opt/traefik/acme.json
  #       state: file
  #       mode: 0600
