---
- hosts: gitea
  gather_facts: true
  become: true
  # vars_files:
  #   - ../vault.yaml

  roles:
    - role: lebergarrett.ansible_common_debian

    - role: geerlingguy.docker
      vars:
        docker_install_compose: true
        docker_users:
          - git
  
  tasks:
    - name: Create the gitea directory
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/gitea"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0755"

    - name: Copy over gitea docker-compose file
      ansible.builtin.copy:
        src: ../files/gitea/docker-compose.yml
        dest: "/home/{{ ansible_user }}/gitea"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0644"