- hosts: gitlab
  gather_facts: true
  become: true
  
  roles:
    - role: geerlingguy.gitlab
      vars:
        gitlab_domain: "kumpdev.com"
        gitlab_external_url: "https://gitlab.kumpdev.com"
        # SSL Self-signed Certificate Configuration.
        gitlab_create_self_signed_cert: true
        gitlab_self_signed_cert_subj: "/C=US/ST=Missouri/L=Saint Louis/O=IT/CN={{ gitlab_domain }}"
        # Use https
        gitlab_redirect_http_to_https: true
        gitlab_ssl_certificate: "/etc/gitlab/ssl/{{ gitlab_domain }}.crt"
        gitlab_ssl_certificate_key: "/etc/gitlab/ssl/{{ gitlab_domain }}.key"
      