---
- hosts: k3s_cluster
  vars_files:
    - ../vault.yaml
  gather_facts: true
  become: true
  roles:
    - role: lebergarrett.ansible_common_debian
    - role: lebergarrett.ansible_nfs_client
      vars:
        sharedrive_location: truenasv2.kumpdev.com:/mnt/Primary/nfs
    - role: ../roles/k3s-prereq
    - role: ../roles/k3s-download

- hosts: k3s_server
  vars_files:
    - ../vault.yaml
  become: true
  roles:
    - role: ../roles/k3s/master

- hosts: k3s_agent
  vars_files:
    - ../vault.yaml
  become: true
  roles:
    - role: ../roles/k3s/node