---
- hosts: qbittorrent
  gather_facts: true
  become: true
  roles:
    - role: lebergarrett.ansible_common_debian
    - role: lebergarrett.ansible_nfs_client
      vars:
        sharedrive_location: truenasv2.kumpdev.com:/mnt/Primary/nfs

  tasks:
    - name: Install openvpn client
      ansible.builtin.apt:
        name: 
          - openvpn
          - openvpn-systemd-resolved

    - name: Configure openvpn client
      ansible.builtin.unarchive:
        src: ../files/openvpn.zip.vault
        dest: /etc/openvpn/client/

    - name: Start and enable openvpn service
      ansible.builtin.systemd:
        name: openvpn-client@mullvad_ch_zrh
        state: started
        enabled: true

    - name: Install qbittorrent-nox
      ansible.builtin.apt:
        name: qbittorrent-nox
    
    - name: Add qbittorrent-nox group
      ansible.builtin.group:
        name: qbittorrent-nox
        state: present

    - name: Add qbittorrent-nox user
      ansible.builtin.user:
        name: qbittorrent-nox
        group: qbittorrent-nox
        system: yes

    - name: Create systemd service file for qbittorrent-nox
      ansible.builtin.copy:
        content: |
          [Unit]
          Description=qBittorrent Command Line Client
          After=network.target
          [Service]
          Type=forking
          User=qbittorrent-nox
          Group=qbittorrent-nox
          UMask=007
          ExecStart=/usr/bin/qbittorrent-nox -d --webui-port=8080
          Restart=on-failure
          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/qbittorrent-nox.service

    - name: Start and enable qbittorrent service
      ansible.builtin.systemd:
        name: qbittorrent-nox.service
        daemon_reload: yes
        state: started
        enabled: yes