---
- hosts: vpn_server
  gather_facts: true
  become: true
  roles:
    - role: lebergarrett.ansible_common_debian
    - role: kyl191.openvpn
      # openvpn_custom_dns: 
      #   - "192.168.0.50"
      openvpn_dualstack: false
      openvpn_server_network: "192.168.50.0"
      openvpn_port: 1194 # default
      # openvpn_push:
      #   - route 192.168.0.0 255.255.255.0
      #   - route 192.168.0.10 255.255.255.0
      clients:
       - Garretts-MacBook-Pro
